version: "2"

linters:
  default: standard
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
